import NumericInput from './NumericInput';
import {useEffect,useState,useRef} from 'react';
import {Button,Dialog,Flex,Text,TextField,Select,Checkbox,Callout,Progress,Spinner,SegmentedControl,Badge} from '@radix-ui/themes';
import {desktop,desktopError,type TagJob,type TagResult} from './desktopBridge';
type Props={projectId:number;relatives:string[];folderItems:{relative:string;caption:string}[];dirtyRelatives:string[];onClose:()=>void;onSave:(items:TagResult[])=>Promise<boolean>};
export default function AutoTagDialog({projectId,relatives,folderItems,dirtyRelatives,onClose,onSave}:Props){
 const key=`auto-tags:${projectId}`;
 const [models,setModels]=useState<{id:string;name:string}[]>([]),[model,setModel]=useState('');
 const initial=useRef<any>((()=>{try{return JSON.parse(localStorage.getItem(key)||'{}');}catch{return {};}})()).current;
 const savedText=(field:string)=>initial[field]||'';
 const [mode,setMode]=useState('missing'),[threshold,setThreshold]=useState(.35),[character,setCharacter]=useState(.85),[remove,setRemove]=useState(true),[prefix,setPrefix]=useState(()=>savedText('prefix')),[blocked,setBlocked]=useState(()=>savedText('blocked'));
 const [job,setJob]=useState<TagJob>({status:'idle'}),[pending,setPending]=useState(false),[error,setError]=useState(''),[stopping,setStopping]=useState(false);
 const [scope,setScope]=useState('selected'),[ready,setReady]=useState(false);
 const targets=scope==='folder'?folderItems.map(i=>i.relative):relatives;
 const eligible=mode==='missing'?targets.filter(r=>!folderItems.find(i=>i.relative===r)?.caption.trim()):targets;
 const dirtyTargets=targets.filter(r=>dirtyRelatives.includes(r));
 const running=['queued','running'].includes(job.status);
 useEffect(()=>{let live=true;Promise.all([desktop()!.tagModels(),desktop()!.tagStatus(projectId)]).then(([catalog,current])=>{if(!live)return;setModels(catalog.models);setModel(catalog.models.find(m=>m.id===(initial.model||current.model?.id))?.id||catalog.models.find(m=>m.name==='wd-v1-4-vit-tagger-v2')?.id||catalog.models[0]?.id||'');setMode(initial.mode??current.mode??'missing');setThreshold(initial.threshold??current.threshold??.35);setCharacter(initial.character??current.character_threshold??.85);setRemove(initial.remove??current.remove_characters??true);if(current.id!==localStorage.getItem(key+':saved'))setJob(current);setReady(true);}).catch(e=>{if(live)setError(desktopError(e));});return()=>{live=false;};},[projectId]);
 useEffect(()=>{if(ready)localStorage.setItem(key,JSON.stringify({model,mode,threshold,character,remove,prefix,blocked}));},[ready,model,mode,threshold,character,remove,prefix,blocked]);
 useEffect(()=>{if(!running)return;let live=true;let timer:ReturnType<typeof setTimeout>;async function poll(){try{const next=await desktop()!.tagStatus(projectId);if(live){setJob(next);if(['queued','running'].includes(next.status))timer=setTimeout(poll,1000);}}catch(e){if(live){setError(desktopError(e));timer=setTimeout(poll,3000);}}}timer=setTimeout(poll,600);return()=>{live=false;clearTimeout(timer);};},[running,projectId]);
 const words=(text:string)=>text.replace(/\n/g,',').split(',').map(t=>t.trim()).filter(Boolean);
 const results=(job.results||[]).map(row=>{if(!row.raw_tags)return row;const denied=new Set(words(blocked).map(t=>t.toLowerCase())),seen=new Set<string>();const tags=[...words(prefix),...(mode==='append'?words(row.previous):[]),...row.raw_tags].filter(tag=>{const name=tag.toLowerCase();if(denied.has(name)||seen.has(name))return false;seen.add(name);return true;});return {...row,caption:tags.join(', '),tag_count:tags.length};});
 const requested=job.requested_relatives||job.inputs?.map(i=>i.relative)||[];
 const scopeChanged=!!job.id&&JSON.stringify([...requested].sort())!==JSON.stringify([...targets].sort());
 const inferenceChanged=!!job.id&&(model!==job.model?.id||mode!==job.mode||threshold!==job.threshold||character!==job.character_threshold||remove!==job.remove_characters);
 const legacyPostChanged=!!job.id&&results.some(r=>!r.raw_tags)&&(prefix!==job.prefix||blocked!==job.blocked);
 const regenerate=scopeChanged||inferenceChanged||legacyPostChanged;
 async function generate(){setPending(true);setError('');setStopping(false);try{setJob(await desktop()!.startTags({project_id:projectId,relatives:targets,scope,model,mode,threshold,character_threshold:character,remove_characters:remove,prefix,blocked}));}catch(e){setError(desktopError(e));}finally{setPending(false);}}
 async function save(){if(regenerate)return;setPending(true);setError('');try{if(await onSave(results)){localStorage.setItem(key+':saved',job.id||'');onClose();}else setError('TXTへ保存できませんでした。生成結果は保持しています。画面のエラーを確認してください。');}catch(e){setError(desktopError(e));}finally{setPending(false);}}
 return <Dialog.Root open onOpenChange={v=>{if(!v&&!pending)onClose();}}><Dialog.Content maxWidth="720px"><Dialog.Title>一括自動タグ生成・TXT出力</Dialog.Title><Dialog.Description size="2" mb="3">生成する範囲を選び、結果を確認してからTXTへ保存します。</Dialog.Description>
 <Flex direction="column" gap="3"><SegmentedControl.Root value={scope} onValueChange={setScope} disabled={running||pending||!ready} aria-label="タグ生成の対象範囲"><SegmentedControl.Item value="selected">選択中の{relatives.length}枚</SegmentedControl.Item><SegmentedControl.Item value="folder">このフォルダの全{folderItems.length}枚</SegmentedControl.Item></SegmentedControl.Root><Flex gap="2" align="center" wrap="wrap"><Badge>対象 {targets.length}枚</Badge><Text size="1" color="gray">処理予定 {eligible.length}枚{mode==='missing'?` · 既存タグあり ${targets.length-eligible.length}枚は除外`:''} · 1回500枚まで</Text></Flex>{dirtyTargets.length>0&&<Text color="amber" size="1">対象に未保存の手編集が{dirtyTargets.length}枚あります。先にTXTへ保存してください。</Text>}
 <label><Text as="div" size="1" mb="1">ComfyUIのタグ付けモデル</Text><Select.Root value={model||undefined} onValueChange={setModel} disabled={running||pending||!ready}><Select.Trigger style={{width:'100%'}} aria-label="タグ付けモデル" placeholder="モデルを確認中"/><Select.Content>{models.map(m=><Select.Item value={m.id} key={m.id}>{m.name}</Select.Item>)}</Select.Content></Select.Root></label>
 <Text size="1" color="gray">既存モデルを直接参照 · CPU処理 · 新規ダウンロードなし</Text>
 <Select.Root value={mode} onValueChange={setMode} disabled={running||pending||!ready}><Select.Trigger aria-label="既存タグの扱い"/><Select.Content><Select.Item value="missing">未タグ付け画像だけ生成</Select.Item><Select.Item value="append">既存タグを残して追加</Select.Item><Select.Item value="replace">既存タグを置換</Select.Item></Select.Content></Select.Root>
 <Flex gap="3" wrap="wrap"><label><Text as="div" size="1">先頭に付けるタグ</Text><TextField.Root aria-label="先頭タグ" placeholder="キャラクター名など" value={prefix} disabled={running||pending||!ready} onChange={e=>setPrefix(e.target.value)}/></label><label><Text as="div" size="1">除外するタグ</Text><TextField.Root aria-label="除外タグ" placeholder="カンマで区切る" value={blocked} disabled={running||pending||!ready} onChange={e=>setBlocked(e.target.value)}/></label></Flex>
 <details><summary>生成の詳細</summary><Flex gap="3" my="3"><label><Text as="div" size="1">一般タグのしきい値</Text><NumericInput aria-label="一般タグしきい値" min={.05} max={.95} step={.05} value={threshold} disabled={running||pending||!ready} onValueChange={setThreshold}/></label><label><Text as="div" size="1">キャラタグのしきい値</Text><NumericInput aria-label="キャラタグしきい値" min={.05} max={.99} step={.05} value={character} disabled={running||pending||!ready||remove} onValueChange={setCharacter}/></label></Flex><Text as="label" size="2"><Checkbox checked={remove} disabled={running||pending||!ready} onCheckedChange={v=>setRemove(v===true)}/> 推定された既存キャラクター名を除外</Text></details>
 {error&&<Callout.Root color="red"><Callout.Text>{error}</Callout.Text></Callout.Root>}
 {ready&&regenerate&&!!results.length&&<Callout.Root color="amber"><Callout.Text>表示中は前の{results.length}枚分の生成結果です。現在の対象・生成条件で生成し直してください。</Callout.Text></Callout.Root>}
 {job.status!=='idle'&&<><Text size="2" role="status">{job.message}</Text><Text size="1" color="gray">生成結果 {results.length}枚 / 実行対象 {job.total||0}枚 · エラー {job.errors?.length||0}枚{job.skipped_existing_count?` · 既存タグあり ${job.skipped_existing_count}枚は除外`:""}</Text>{running&&<Progress value={job.total?100*(job.done||0)/job.total:0}/>}<div className="tag-result-list">{results.map(item=><div key={item.relative}><Text as="div" weight="medium" size="2">{item.relative} · {item.tag_count}タグ</Text><Text as="p" size="2">{item.caption||'検出されたタグなし'}</Text></div>)}</div>{job.errors?.map(item=><Text key={item.relative} color="red" size="1">{item.relative}：{item.message}</Text>)}{!!results.length&&<Text color="amber" size="1">まだTXTには保存していません。</Text>}</>}
 <Flex justify="end" gap="3" wrap="wrap" mt="3"><Button variant="soft" color="gray" disabled={pending} onClick={onClose}>{running?'閉じる（処理は継続）':'閉じる'}</Button>{running?<Button color="amber" variant="soft" disabled={stopping} onClick={()=>{setStopping(true);void desktop()!.stopTags(projectId).catch(e=>{setStopping(false);setError(desktopError(e));});}}>{stopping?'停止待ち':'生成を停止'}</Button>:<Button variant="soft" disabled={pending||!ready||!model||!eligible.length||targets.length>500||!!dirtyTargets.length||threshold<.05||threshold>.95||character<.05||character>.99} title={!ready?'タグ付けモデルを確認中です':!model?'タグ付けモデルを選んでください':!targets.length?'対象の画像がありません':!eligible.length?'処理する画像がありません（既存タグありの画像は「未タグ付け画像だけ生成」では除外されます。「既存タグを残して追加」などに切り替えてください）':targets.length>500?'1回に処理できるのは500枚までです。対象を絞ってください':dirtyTargets.length?'未保存の手編集があります。先にTXTへ保存してください':(threshold<.05||threshold>.95||character<.05||character>.99)?'しきい値の範囲を確認してください（一般0.05〜0.95、キャラ0.05〜0.99）':undefined} onClick={()=>void generate()}>{pending?<Spinner/>:null}{`対象${eligible.length}枚のタグを生成`}</Button>}<Button disabled={running||pending||!ready||!results.length||regenerate||!!dirtyTargets.length} title={running?'生成中です。完了後に保存できます':!results.length?'先にタグを生成してください':regenerate?'対象や生成条件が変わりました。もう一度タグを生成してください':dirtyTargets.length?'未保存の手編集があります。先にTXTへ保存してください':undefined} onClick={()=>void save()}>{results.length}枚のTXTへ一括保存</Button></Flex>
 </Flex></Dialog.Content></Dialog.Root>;
}
