import {useState} from 'react';
import {Button,Dialog,Flex,Text,Checkbox,Spinner,Callout} from '@radix-ui/themes';
import {apiGet,apiPost} from '../../lib/api';
type Kind='training'|'preview'|'weights';
type Group={files:number;bytes:number};
type Row={run_id:number;status:string;epoch:number;busy:boolean}&Record<Kind,Group>;
const labels:Record<Kind,string>={training:'前処理キャッシュ',preview:'プレビュー画像',weights:'学習済みLoRA'};
export default function BulkRunCleanup({projectId,onChanged}:{projectId:number;onChanged:()=>void}){
 const [open,setOpen]=useState(false),[rows,setRows]=useState<Row[]>([]),[selected,setSelected]=useState<number[]>([]),[kinds,setKinds]=useState<Kind[]>(['training']),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const chosen=rows.filter(r=>selected.includes(r.run_id)),files=chosen.reduce((n,r)=>n+kinds.reduce((m,k)=>m+r[k].files,0),0),bytes=chosen.reduce((n,r)=>n+kinds.reduce((m,k)=>m+r[k].bytes,0),0);
 async function inspect(){setOpen(true);setBusy(true);setError('');setNotice('');setConfirm(false);setSelected([]);try{setRows((await apiGet<{runs:Row[]}>(`/training/project-cleanup/${projectId}`)).runs);}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function remove(){setBusy(true);setError('');try{const r=await apiPost<{deleted_files:number}>(`/training/project-cleanup/${projectId}`,{run_ids:selected,kinds,confirm:true});setNotice(`${r.deleted_files}ファイルを削除しました。`);setConfirm(false);setSelected([]);setRows((await apiGet<{runs:Row[]}>(`/training/project-cleanup/${projectId}`)).runs);onChanged();}catch(e){setError(String(e));}finally{setBusy(false);}}
 return <><Button size="2" variant="soft" color="gray" onClick={()=>void inspect()}>過去Run・キャッシュを一括整理</Button><Dialog.Root open={open} onOpenChange={v=>{if(!busy)setOpen(v);}}><Dialog.Content maxWidth="820px" onEscapeKeyDown={e=>{e.preventDefault();e.stopPropagation();if(!busy)setOpen(false);}}><Dialog.Title>過去Runを選んで一括削除</Dialog.Title><Dialog.Description size="2">元画像・タグ・ベースモデル・学習ログは残します。選択した種類の保存物だけを削除します。</Dialog.Description><Flex wrap="wrap" gap="4" my="3">{(Object.keys(labels) as Kind[]).map(k=><Text as="label" size="2" key={k}><Checkbox checked={kinds.includes(k)} disabled={busy} onCheckedChange={v=>{setKinds(a=>v===true?[...a,k]:a.filter(x=>x!==k));setConfirm(false);}}/> {labels[k]}</Text>)}</Flex><Flex gap="3" mb="2"><Button size="2" variant="soft" disabled={busy} onClick={()=>{setSelected(rows.filter(r=>!r.busy).map(r=>r.run_id));setConfirm(false);}}>選べるRunを全選択</Button><Button size="2" variant="ghost" disabled={busy} onClick={()=>{setSelected([]);setConfirm(false);}}>選択解除</Button></Flex><div className="wb-bulk-run-list">{rows.map(r=><label className="wb-bulk-run-row" key={r.run_id}><Checkbox aria-label={`Run ${r.run_id}を選択`} disabled={busy||r.busy} checked={selected.includes(r.run_id)} onCheckedChange={v=>{setSelected(a=>v===true?[...a,r.run_id]:a.filter(x=>x!==r.run_id));setConfirm(false);}}/><div><Text as="div" size="2" weight="medium">Run #{r.run_id} · Epoch {r.epoch}{r.busy?' · 実行中／生成待ち':''}</Text><Text as="div" size="1" color="gray">前処理 {r.training.files}件 · プレビュー {r.preview.files}件 · LoRA {r.weights.files}件</Text></div><Text size="2">{(kinds.reduce((n,k)=>n+r[k].bytes,0)/1048576).toFixed(1)} MB</Text></label>)}</div><Text as="p" size="2" mt="3">選択 {selected.length} Run · {files}ファイル · 対象容量 {(bytes/1048576).toFixed(1)} MB</Text>{kinds.includes('weights')&&<Text as="p" size="1" color="amber">学習済みLoRAを削除すると、その重みから継続・再生成できなくなります。</Text>}{confirm&&<Callout.Root color="amber" mt="2"><Callout.Text>Run {selected.map(x=>`#${x}`).join('、')} の {kinds.map(k=>labels[k]).join('・')} を削除します。この操作は取り消せません。</Callout.Text></Callout.Root>}{error&&<Text as="p" color="red">{error}</Text>}{notice&&<Text as="p" role="status">{notice}</Text>}<Flex justify="end" gap="3" mt="4"><Button variant="soft" color="gray" disabled={busy} onClick={()=>setOpen(false)}>{confirm?'キャンセル':'閉じる'}</Button><Button color="red" disabled={busy||!selected.length||!kinds.length||!files} onClick={()=>confirm?void remove():setConfirm(true)}>{busy?<Spinner/>:confirm?'選択した対象を削除する':'選択した対象の削除を確認'}</Button></Flex></Dialog.Content></Dialog.Root></>;
}
