import {useEffect,useRef,useState} from 'react';
import {Button,IconButton,SegmentedControl,TextArea,TextField} from '@radix-ui/themes';
import {Copy,Scissors,X,Undo2,Redo2,Pencil,ClipboardPaste} from 'lucide-react';
import {Slider} from 'radix-ui';
import './editor-components.css';
export const splitTags=(text:string)=>text.split(/[,\n]/).map(t=>t.trim()).filter(Boolean);
export const uniqueTags=(tags:string[])=>{const seen=new Set<string>();return tags.filter(t=>{const key=t.toLocaleLowerCase();if(seen.has(key))return false;seen.add(key);return true;});};
type Props={value:string;storageKey:string;disabled:boolean;triggerTags?:string[];onChange:(v:string)=>void;onSave:()=>void};
type History={past:string[];future:string[];value:string};
export default function CaptionEditor({value,storageKey,disabled,triggerTags=[],onChange,onSave}:Props){
 const [mode,setMode]=useState('tags'),[selected,setSelected]=useState<number[]>([]),[entry,setEntry]=useState(''),[editing,setEditing]=useState<number|null>(null),[message,setMessage]=useState('');
 const [history,setHistory]=useState<History>(()=>{try{const h=JSON.parse(localStorage.getItem(storageKey)||'null');if(h?.value===value)return h;}catch{}return{past:[],future:[],value};});
 const current=useRef(value),anchor=useRef<number|null>(null),input=useRef<HTMLInputElement>(null),group=useRef<HTMLDivElement>(null),composing=useRef(false);
 const [zoom,setZoom]=useState(()=>{try{const n=Number(localStorage.getItem('studio:tag-chip-zoom'));return Number.isFinite(n)&&n>=60&&n<=160?n:100;}catch{return 100;}});
 useEffect(()=>{try{localStorage.setItem('studio:tag-chip-zoom',String(zoom));}catch{}},[zoom]);
 const tags=splitTags(value);
 function paste(text:string){const at=selected.length?Math.max(...selected)+1:tags.length;commit(uniqueTags([...tags.slice(0,at),...splitTags(text),...tags.slice(at)]).join(', '));}
 useEffect(()=>{if(value!==current.current){current.current=value;setHistory({past:[],future:[],value});setSelected([]);setEditing(null);}},[value]);
 useEffect(()=>{localStorage.setItem(storageKey,JSON.stringify(history));},[storageKey,history]);
 function commit(next:string){if(disabled||next===current.current)return;const old=current.current;current.current=next;setHistory(h=>({past:[...h.past,old].slice(-50),future:[],value:next}));onChange(next);setSelected([]);setMessage('下書きに反映しました');}
 function undo(){if(disabled||!history.past.length)return;const next=history.past[history.past.length-1]!;setHistory({past:history.past.slice(0,-1),future:[current.current,...history.future],value:next});current.current=next;onChange(next);setSelected([]);setEditing(null);setEntry('');}
 function redo(){if(disabled||!history.future.length)return;const next=history.future[0];setHistory({past:[...history.past,current.current],future:history.future.slice(1),value:next});current.current=next;onChange(next);setSelected([]);setEditing(null);setEntry('');}
 function add(){if(composing.current||disabled)return;const additions=splitTags(entry);if(!additions.length)return;const next=editing===null?uniqueTags([...tags,...additions]):uniqueTags(tags.flatMap((t,i)=>i===editing?additions:[t]));commit(next.join(', '));setEntry('');setEditing(null);input.current?.focus();}
 function remove(ids:number[]){commit(tags.filter((_,i)=>!ids.includes(i)).join(', '));setEditing(null);setEntry('');}
 async function copy(cut=false){const source=current.current;const ids=selected.length?selected:tags.map((_,i)=>i);const text=tags.filter((_,i)=>ids.includes(i)).join(', ');try{await navigator.clipboard.writeText(text);if(cut&&current.current!==source){setMessage('編集中の変更を保護しました。コピーのみ完了しています。');return;}if(cut)remove(ids);setMessage(cut?'切り取りました':'コピーしました');}catch{setMessage('コピーできませんでした。タグは変更していません。');}}
 const beginEdit=(i:number)=>{setEditing(i);setEntry(tags[i]);input.current?.focus();};
 function choose(i:number,e:React.MouseEvent){if(disabled)return;if(e.shiftKey&&anchor.current!==null){const lo=Math.min(anchor.current,i),hi=Math.max(anchor.current,i);setSelected(Array.from({length:hi-lo+1},(_,j)=>lo+j));}else if(e.ctrlKey||e.metaKey){setSelected(s=>s.includes(i)?s.filter(n=>n!==i):[...s,i]);anchor.current=i;}else{setSelected([i]);anchor.current=i;}}
 return <div className="caption-component" onKeyDown={e=>{if(e.nativeEvent.isComposing||composing.current)return;const ctrl=e.ctrlKey||e.metaKey;if(ctrl&&e.key.toLowerCase()==='s'){e.preventDefault();onSave();}if(e.target===input.current&&ctrl&&['z','y'].includes(e.key.toLowerCase()))return;if(ctrl&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();}if(ctrl&&e.key.toLowerCase()==='y'){e.preventDefault();redo();}}}>
  <div className="caption-controls"><SegmentedControl.Root value={mode} onValueChange={setMode} aria-label="キャプションの編集方式"><SegmentedControl.Item value="tags">タグ</SegmentedControl.Item><SegmentedControl.Item value="text">文章</SegmentedControl.Item></SegmentedControl.Root><div><IconButton size="1" variant="ghost" aria-label="タグ編集を元に戻す" title="元に戻す Ctrl+Z" disabled={disabled||!history.past.length} onClick={undo}><Undo2 size={16}/></IconButton><IconButton size="1" variant="ghost" aria-label="タグ編集をやり直す" title="やり直す Ctrl+Shift+Z" disabled={disabled||!history.future.length} onClick={redo}><Redo2 size={16}/></IconButton></div></div>
  {mode==='tags'?<>
   <div className="tag-zoom"><span>表示倍率</span><Slider.Root className="rt-SliderRoot rt-r-size-1 rt-variant-surface" min={60} max={160} step={5} value={[zoom]} onValueChange={v=>setZoom(v[0])}><Slider.Track className="rt-SliderTrack"><Slider.Range className="rt-SliderRange"/></Slider.Track><Slider.Thumb className="rt-SliderThumb" aria-label="タグの表示倍率" aria-valuetext={`${zoom}%`}/></Slider.Root><button type="button" title="標準の100%に戻す" aria-label="タグの表示倍率を100%に戻す" onClick={()=>setZoom(100)}>{zoom}%</button></div>
   <div style={{'--tag-scale':zoom/100} as React.CSSProperties} className="tag-list" ref={group} tabIndex={0} aria-label="タグを選択" onPaste={e=>{e.preventDefault();paste(e.clipboardData.getData('text'));}} onKeyDown={e=>{if(e.nativeEvent.isComposing)return;const ctrl=e.ctrlKey||e.metaKey;if(ctrl&&e.key.toLowerCase()==='a'){e.preventDefault();setSelected(tags.map((_,i)=>i));}if(ctrl&&['c','x'].includes(e.key.toLowerCase())){e.preventDefault();void copy(e.key.toLowerCase()==='x');}if(['Delete','Backspace'].includes(e.key)&&selected.length){e.preventDefault();remove(selected);}if(e.key==='Escape')setSelected([]);if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const i=Math.max(0,Math.min(tags.length-1,(selected[selected.length-1]??-1)+(e.key==='ArrowRight'?1:-1)));setSelected([i]);group.current?.querySelector<HTMLButtonElement>(`[data-tag-index="${i}"]`)?.focus();}}}>
    {tags.map((tag,i)=><span className={`tag-chip ${selected.includes(i)?'is-selected':''} ${triggerTags.some(t=>t.toLowerCase()===tag.toLowerCase())?'is-trigger':''}`} key={`${i}:${tag}`}><button type="button" data-tag-index={i} aria-pressed={selected.includes(i)} disabled={disabled} className="tag-label" title={tag} onClick={e=>choose(i,e)} onDoubleClick={()=>beginEdit(i)}>{triggerTags.some(t=>t.toLowerCase()===tag.toLowerCase())&&<span className="tag-trigger-mark" title="トリガータグ">● </span>}{tag}</button><button type="button" className="tag-remove" aria-label={`${tag}を削除`} title="このタグを削除" disabled={disabled} onClick={()=>remove([i])}><X size={13}/></button></span>)}{!tags.length&&<span className="tag-hint">下の欄からタグを追加</span>}
   </div>
   <div className="tag-actions"><span>{selected.length?`${selected.length}個選択`:`${tags.length}タグ`}</span><IconButton size="1" variant="ghost" aria-label="タグをコピー" title="選択タグをコピー（未選択時は全タグ）" disabled={disabled||!tags.length} onClick={()=>void copy()}><Copy size={15}/></IconButton><IconButton size="1" variant="ghost" aria-label="選択タグを切り取り" title="選択タグを切り取り" disabled={disabled||!selected.length} onClick={()=>void copy(true)}><Scissors size={15}/></IconButton><IconButton size="1" variant="ghost" aria-label="選択タグを編集" title="選択タグを編集" disabled={disabled||selected.length!==1} onClick={()=>beginEdit(selected[0])}><Pencil size={15}/></IconButton><IconButton size="1" variant="ghost" aria-label="選択タグを削除" title="選択タグを削除" disabled={disabled||!selected.length} onClick={()=>remove(selected)}><X size={15}/></IconButton><IconButton size="1" variant="ghost" aria-label="タグを貼り付け" title="タグを貼り付け" disabled={disabled} onClick={async()=>{try{const t=await navigator.clipboard.readText();paste(t);}catch{setMessage('タグ領域を選んでCtrl+Vで貼り付けてください。');}}}><ClipboardPaste size={15}/></IconButton><Button size="1" variant="ghost" disabled={disabled||uniqueTags(tags).length===tags.length} title={uniqueTags(tags).length===tags.length?'重複しているタグはありません':'同じタグを1つにまとめます'} onClick={()=>commit(uniqueTags(tags).join(', '))}>重複整理</Button></div>
   <div className="tag-entry"><TextField.Root ref={input} aria-label={editing===null?'タグを追加':'タグ名を編集'} placeholder={editing===null?'タグを追加（カンマで複数）':'タグ名を編集'} value={entry} disabled={disabled} onChange={e=>setEntry(e.target.value)} onCompositionStart={()=>{composing.current=true;}} onCompositionEnd={()=>{composing.current=false;}} onKeyDown={e=>{if(e.nativeEvent.isComposing||composing.current)return;if(e.key==='Enter'){e.preventDefault();add();}if(e.key==='Escape'){setEntry('');setEditing(null);}}}/><Button size="2" disabled={disabled||!entry.trim()} aria-label={editing===null?'タグを追加':'タグ名の変更を適用'} title={disabled?'この画像は編集できません':!entry.trim()?'左の入力欄にタグを入力すると使えます（Enterでも確定）':undefined} onClick={add}>{editing===null?'追加':'適用'}</Button>{editing!==null&&<IconButton variant="ghost" aria-label="タグ名編集を取消" onClick={()=>{setEntry('');setEditing(null);}}><X size={15}/></IconButton>}</div>
  </>:<TextArea id="df-caption" aria-label="キャプション本文" readOnly={disabled} className="df-caption" resize="vertical" value={value} onChange={e=>commit(e.target.value)} placeholder="キャプションを自由に入力"/>}
  <div className="caption-feedback" role="status">{message}</div>
 </div>;
}
