import {useEffect,useState} from 'react';
import {Button,Flex,Text,Select,Callout,IconButton} from '@radix-ui/themes';
import {Slider} from 'radix-ui';
import {X} from 'lucide-react';
import {apiGet,apiPost} from '../../lib/api';
import ModelPicker from './ModelPicker';
import NumericInput from './NumericInput';
import type {Config} from './TrainingDock';
export type ExtraLora={name:string;strength:number};
function Strength({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void}){return <div className="wb-lora-strength"><Text size="1">{label}</Text><Flex gap="3" align="center"><Slider.Root className="rt-SliderRoot rt-r-size-1 rt-variant-surface" min={0} max={2} step={.05} value={[value]} onValueChange={v=>onChange(v[0])} style={{flex:1}}><Slider.Track className="rt-SliderTrack"><Slider.Range className="rt-SliderRange"/></Slider.Track><Slider.Thumb className="rt-SliderThumb" aria-label={label} aria-valuetext={`${value.toFixed(2)}倍`}/></Slider.Root><NumericInput aria-label={`${label}の数値`} value={value} min={0} max={2} step={.05} style={{width:88}} onValueChange={onChange}/></Flex></div>}
export default function ComfyPreviewControls({projectId,runId,config,onChange}:{projectId:number;runId:number|null;config:Config;onChange:(c:Partial<Config>)=>void}){
 const [loras,setLoras]=useState<string[]>([]),[checkpoints,setCheckpoints]=useState<{id:number;epoch:number;step:number|null;validation_status:string}[]>([]),[chosen,setChosen]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function load(){const r=await apiGet<{loras:string[]}>('/previews/comfy-loras',30000);setLoras(r.loras);}
 useEffect(()=>{void load().catch(e=>setError(e.message));},[]);
 useEffect(()=>{if(!runId){setCheckpoints([]);setChosen('');return;}let live=true;const poll=()=>apiGet<{checkpoints:typeof checkpoints}>(`/training/runs/${runId}/checkpoints`).then(r=>{if(live){const rows=r.checkpoints.filter(c=>!['invalid','deleted'].includes(c.validation_status)).sort((a,b)=>b.epoch-a.epoch||b.id-a.id);setCheckpoints(rows);setChosen(old=>rows.some(r=>String(r.id)===old)?old:rows[0]?String(rows[0].id):'');}}).catch(e=>{if(live)setError(e.message);});void poll();const timer=setInterval(poll,5000);return()=>{live=false;clearInterval(timer);};},[runId]);
 const extras=config.preview_extra_loras||[];
 async function render(){if(!chosen)return;setBusy(true);setError('');try{await apiPost(`/previews/render-checkpoint/${chosen}`,{profile_id:config.preview_profile_snapshot_id,base_checkpoint_path:config.preview_base_checkpoint_path||config.base_checkpoint_path,lora_strength:config.preview_lora_strength??1,extra_loras:extras,steps:config.preview_steps,cfg:config.preview_cfg},'POST',undefined,60000);setNotice('生成を予約しました。結果はギャラリーへ表示します。');}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 return <div className="wb-comfy-preview-controls"><Text as="p" size="1" color="gray">生成先：接続中のComfyUI。強度の変更は次の生成に反映します。</Text><Strength label="学習LoRAの適用強度" value={config.preview_lora_strength??1} onChange={v=>onChange({preview_lora_strength:v})}/>{extras.map((lora,i)=><div key={lora.name} className="wb-extra-lora"><Flex align="center" gap="2"><Text size="1" title={lora.name} style={{flex:1,overflowWrap:'anywhere'}}>{lora.name.split(/[\\/]/).pop()}</Text><IconButton size="1" variant="ghost" aria-label={`${lora.name}を追加LoRAから外す`} onClick={()=>onChange({preview_extra_loras:extras.filter((_,j)=>j!==i)})}><X size={14}/></IconButton></Flex><Strength label={`追加LoRA ${i+1}の強度`} value={lora.strength} onChange={v=>onChange({preview_extra_loras:extras.map((r,j)=>j===i?{...r,strength:v}:r)})}/></div>)}{extras.length<8&&<ModelPicker label="追加LoRA（組み合わせ）" value="" choices={loras.filter(name=>!extras.some(e=>e.name===name)).map(name=>({name:name.split(/[\\/]/).pop()||name,path:name}))} onChange={name=>onChange({preview_extra_loras:[...extras,{name,strength:1}]})} onRefresh={load}/>}<Text as="p" size="1" color="gray">同じモデル系統のLoRAを選んでください。追加分は表示順に適用します。</Text><Flex gap="2" align="center" wrap="wrap" mt="3"><Select.Root value={chosen||undefined} onValueChange={setChosen} disabled={!checkpoints.length||busy}><Select.Trigger aria-label="比較生成する保存済みLoRA" placeholder="保存済みエポック"/><Select.Content>{checkpoints.map(c=><Select.Item key={c.id} value={String(c.id)}>Epoch {c.epoch} · Step {c.step??'—'}</Select.Item>)}</Select.Content></Select.Root><Button size="2" style={{flex:1,minHeight:36}} disabled={!chosen||busy} title={busy?'生成を予約中です':!chosen?'保存済みのエポックがまだありません。学習でエポックが保存されると選べます':undefined} onClick={()=>void render()}>この条件でComfyUI生成</Button></Flex>{notice&&<Text as="p" size="1" role="status">{notice}</Text>}{error&&<Callout.Root color="red" size="1" mt="2"><Callout.Text>{error}</Callout.Text></Callout.Root>}</div>;
}
