import {useEffect,useRef,useState} from 'react';
import {Button,Dialog,Flex,IconButton,Text} from '@radix-ui/themes';
import {X,ZoomIn,ZoomOut,ChevronLeft,ChevronRight,Expand} from 'lucide-react';
import {API_BASE} from '../../lib/api';
type ImageItem={relative:string;name:string;width:number;height:number;modified:number};
export default function DatasetImageViewer({projectId,item,items,onChange,onClose,returnFocus}:{projectId:number;item:ImageItem;items:ImageItem[];onChange:(item:ImageItem)=>void;onClose:()=>void;returnFocus:HTMLElement|null}){
 const [scale,setScale]=useState<number|null>(null),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[natural,setNatural]=useState({width:item.width,height:item.height});const viewport=useRef<HTMLDivElement>(null);
 const [box,setBox]=useState({width:window.innerWidth,height:window.innerHeight-100});
 useEffect(()=>{const node=viewport.current;if(!node)return;const update=()=>setBox({width:node.clientWidth,height:node.clientHeight});update();const observer=new ResizeObserver(update);observer.observe(node);return()=>observer.disconnect();},[]);
 const fitScale=Math.max(.01,Math.min((box.width-32)/natural.width,(box.height-32)/natural.height,1));
 const index=items.findIndex(i=>i.relative===item.relative);
 useEffect(()=>{setScale(null);setLoaded(false);setError('');setNatural({width:item.width,height:item.height});viewport.current?.scrollTo(0,0);},[item.relative,item.modified]);
 const fit=()=>{const box=viewport.current;return box?Math.min((box.clientWidth-32)/natural.width,(box.clientHeight-32)/natural.height,1)*100:100;};
 function zoom(direction:number){setScale(old=>Math.max(10,Math.min(800,Math.round((old??fit())*(direction>0?1.25:.8)))));}
 function next(delta:number){const target=items[index+delta];if(target)onChange(target);}
 return <Dialog.Root open onOpenChange={open=>{if(!open)onClose();}}><Dialog.Content className="df-image-viewer" style={{position:'fixed',inset:0,margin:0,width:'100vw',height:'100dvh',maxWidth:'100vw',maxHeight:'100dvh',borderRadius:0,padding:0,transform:'none'}} onCloseAutoFocus={e=>{e.preventDefault();returnFocus?.focus({preventScroll:true});}} onKeyDown={e=>{if(e.target instanceof HTMLInputElement)return;if(e.key==='ArrowLeft'){e.preventDefault();next(-1);}else if(e.key==='ArrowRight'){e.preventDefault();next(1);}else if(e.key==='+'||e.key==='='){e.preventDefault();zoom(1);}else if(e.key==='-'){e.preventDefault();zoom(-1);}}}>
 <Flex className="df-viewer-toolbar" gap="2" align="center" wrap="wrap"><Dialog.Title style={{margin:0,fontSize:13,minWidth:0,flex:1,overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{item.name}</Dialog.Title><Text size="1" color="gray">{natural.width} × {natural.height}{index>=0?` · ${index+1}/${items.length}`:''}</Text><IconButton size="1" variant="soft" aria-label="前の画像" disabled={index<=0} onClick={()=>next(-1)}><ChevronLeft size={17}/></IconButton><IconButton size="1" variant="soft" aria-label="次の画像" disabled={index<0||index>=items.length-1} onClick={()=>next(1)}><ChevronRight size={17}/></IconButton><Button size="1" variant={scale===null?'solid':'soft'} onClick={()=>{setScale(null);viewport.current?.scrollTo(0,0);}}><Expand size={14}/>画面に合わせる</Button><Button size="1" variant={scale===100?'solid':'soft'} onClick={()=>setScale(100)}>原寸 100%</Button><IconButton size="1" variant="soft" aria-label="画像を縮小" onClick={()=>zoom(-1)}><ZoomOut size={17}/></IconButton><Text size="1" style={{minWidth:40,textAlign:'center'}}>{scale===null?'Fit':`${scale}%`}</Text><IconButton size="1" variant="soft" aria-label="画像を拡大" onClick={()=>zoom(1)}><ZoomIn size={17}/></IconButton><Dialog.Close><IconButton size="2" variant="soft" aria-label="拡大表示を閉じる"><X size={19}/></IconButton></Dialog.Close></Flex>
 <Dialog.Description className="df-viewer-hint">原画像を表示 · ← →で前後の画像 · ＋ −で倍率変更 · Escで閉じる</Dialog.Description>
 <div ref={viewport} className="df-viewer-viewport" aria-label="拡大画像の表示領域"><div className={`df-viewer-canvas ${scale===null?'is-fit':''}`} style={scale===null?undefined:{width:natural.width*scale/100+32,height:natural.height*scale/100+32}}>{!loaded&&!error&&<Text className="df-viewer-loading" size="2">原画像を読み込み中…</Text>}{error?<Text color="red">{error}</Text>:<img key={`${item.relative}:${item.modified}`} draggable={false} alt={item.name} src={`${API_BASE}/dataset-files/${projectId}/image?relative=${encodeURIComponent(item.relative)}&v=${item.modified}`} style={{width:natural.width*(scale===null?fitScale:scale/100),height:natural.height*(scale===null?fitScale:scale/100),maxWidth:'none',maxHeight:'none'}} onLoad={e=>{setNatural({width:e.currentTarget.naturalWidth,height:e.currentTarget.naturalHeight});setLoaded(true);}} onError={()=>setError('原画像を読み込めませんでした。ファイルの移動・削除を確認してください。')}/>}</div></div>
 </Dialog.Content></Dialog.Root>;
}
