import {useEffect,useState} from 'react';
import {Button,Flex,Text,Callout,Spinner,Select} from '@radix-ui/themes';
import {apiGet,apiPost,apiDelete} from '../../lib/api';
import {desktop,type TagJob} from './desktopBridge';
type Reference={name:string;sha256:string;source_relative:string;reference_relative:string;image_url:string;prompt:string|null;profile_snapshot_id:number|null};
export default function EvaluationReference({projectId,runId,family,onProfile}:{projectId:number;runId:number|null;family:string;onProfile:(p:any)=>void}){
 const [reference,setReference]=useState<Reference|null>(null),[runReference,setRunReference]=useState<Reference|null>(null),[models,setModels]=useState<{id:string;name:string}[]>([]),[model,setModel]=useState(''),[job,setJob]=useState<TagJob|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function refresh(){const r=await apiGet<{reference:Reference|null;run_reference:Reference|null}>(`/evaluation/${projectId}${runId?`?run_id=${runId}`:''}`);setReference(r.reference);setRunReference(r.run_reference);}
 useEffect(()=>{void refresh().catch(e=>setError(e.message));const changed=(e:Event)=>{if((e as CustomEvent).detail.projectId===projectId)void refresh();};window.addEventListener('evaluation-reference-changed',changed);return()=>window.removeEventListener('evaluation-reference-changed',changed);},[projectId,runId]);
 useEffect(()=>{if(!desktop())return;void desktop()!.tagModels().then(r=>{setModels(r.models);setModel(r.models.find(m=>m.name==='wd-v1-4-vit-tagger-v2')?.id||r.models[0]?.id||'');}).catch(e=>setError(String(e)));},[]);
 useEffect(()=>{if(!desktop()||!reference||reference.profile_snapshot_id)return;let alive=true;void desktop()!.tagStatus(projectId).then(current=>{if(alive&&current.inputs?.some(i=>i.relative===reference.reference_relative))setJob(current);}).catch(e=>{if(alive)setError(String(e));});return()=>{alive=false;};},[projectId,reference?.sha256,reference?.profile_snapshot_id]);
 const running=job&&['queued','running'].includes(job.status);
 useEffect(()=>{if(!running)return;let alive=true;let timer:ReturnType<typeof setTimeout>;async function poll(){try{const next=await desktop()!.tagStatus(projectId);if(alive){if(next.id!==job?.id){setError('別のタグ生成が開始されました。評価タグを生成し直してください。');setJob(null);return;}setJob(next);if(['queued','running'].includes(next.status))timer=setTimeout(poll,1000);}}catch(e){if(alive){setError(String(e));timer=setTimeout(poll,3000);}}}timer=setTimeout(poll,1000);return()=>{alive=false;clearTimeout(timer);};},[running,projectId,job?.id]);
 async function clear(){setBusy(true);setError('');try{await apiDelete(`/evaluation/${projectId}`);setReference(null);setJob(null);window.dispatchEvent(new CustomEvent('evaluation-reference-changed',{detail:{projectId}}));}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function choose(){setBusy(true);setError('');try{const r=await apiPost<{reference:Reference}>(`/evaluation/${projectId}`,{},'POST',undefined,60000);setReference(r.reference);setJob(null);window.dispatchEvent(new CustomEvent('evaluation-reference-changed',{detail:{projectId}}));}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function generate(){if(!reference||!desktop())return;setBusy(true);setError('');try{const current=await desktop()!.tagStatus(projectId);if(['running','queued'].includes(current.status))throw Error('別のタグ生成が実行中です。完了後に実行してください。');setJob(await desktop()!.startTags({project_id:projectId,relatives:[reference.reference_relative],model,mode:'replace',scope:'selected',threshold:.35,character_threshold:.85,remove_characters:true,prefix:'',blocked:''}));}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function applyTags(){if(!job?.id)return;setBusy(true);setError('');try{const r=await apiPost<{reference:Reference;profile:any}>(`/evaluation/${projectId}/use-tags`,{job_id:job.id,model_family:family});setReference(r.reference);onProfile(r.profile);setJob(null);}catch(e){setError(String(e));}finally{setBusy(false);}}
 const shown=reference;
 return <section className="wb-evaluation-reference" aria-label="評価用画像"><Flex justify="between" align="center" gap="2"><Text size="2" weight="medium">評価用画像 · 次回の学習用</Text><Flex gap="2"><Button size="1" variant="soft" disabled={busy||!!running} onClick={()=>void choose()}>自動で1枚選ぶ</Button>{reference&&<Button size="1" variant="ghost" disabled={busy||!!running} onClick={()=>void clear()}>解除</Button>}</Flex></Flex>{shown?<div style={{display:'flex',gap:12,marginTop:10,alignItems:'start'}}><img src={shown.image_url} alt={`評価用：${shown.name}`} style={{width:120,maxHeight:150,objectFit:'contain',background:'var(--gray-2)'}}/><div style={{minWidth:0}}><Text as="div" size="1" style={{overflowWrap:'anywhere'}}>{shown.name}</Text><Text as="p" size="1" color="gray">同じ内容の画像を学習対象から除外します。</Text>{shown.prompt&&<details><summary>比較に使うタグ</summary><Text size="1">{shown.prompt}</Text></details>}</div></div>:<Text as="p" size="1" color="gray">自動選択、または画像詳細の「評価用画像にする」で指定できます。</Text>}{runReference&&<details className="wb-frozen-evaluation" style={{marginTop:10}}><summary>Run #{runId} の保存済み比較基準</summary><Flex gap="3" mt="2" align="start"><img src={runReference.image_url} alt={`保存済み比較基準：${runReference.name}`} style={{width:100,maxHeight:120,objectFit:'contain'}}/><div><Text as="div" size="1">{runReference.name}</Text><Text as="p" size="1" color="gray">このRunの生成画像に対応する固定の基準です。</Text></div></Flex></details>}{reference&&<><Flex gap="2" wrap="wrap" mt="2"><Select.Root value={model||undefined} onValueChange={setModel} disabled={busy||!!running}><Select.Trigger aria-label="評価画像のタグ抽出モデル" placeholder="タグ抽出モデル"/><Select.Content>{models.map(m=><Select.Item key={m.id} value={m.id}>{m.name}</Select.Item>)}</Select.Content></Select.Root><Button size="1" disabled={!desktop()||!model||busy||!!running} onClick={()=>void generate()}>{running?<Spinner/>:null}画像から評価タグを生成</Button></Flex>{job&&<Text as="p" size="1">{job.message||job.status}</Text>}{job?.errors?.map(e=><Text as="p" size="1" color="red" key={e.relative}>{e.message}</Text>)}{!desktop()&&<Text as="p" size="1" color="gray">画像からのタグ生成はデスクトップ版で利用できます。</Text>}{job?.status==='done'&&job.results?.length===1&&<><Text as="p" size="1">{job.results[0].caption}</Text><Button size="1" disabled={busy} onClick={()=>void applyTags()}>このタグをプレビュー条件に使う</Button></>}</>}{error&&<Callout.Root color="red" size="1" mt="2"><Callout.Text>{error}</Callout.Text></Callout.Root>}</section>;
}
