import NumericInput from './NumericInput';
import {useEffect,useRef,useState} from 'react';
import {Button,Dialog,Flex,Text,TextField,Select,Checkbox,Spinner,Callout,Progress,Badge} from '@radix-ui/themes';
import {desktop,desktopError,type NormalizePreview,type NormalizeSettings} from './desktopBridge';
type Props={projectId:number;relatives:string[];onClose:()=>void;onCreated:(folder:string,relatives:string[])=>void};
export default function PreprocessDialog({projectId,relatives,onClose,onCreated}:Props){
 const key=`preprocess-settings:${projectId}`;const saved=useRef<any>((()=>{try{return JSON.parse(localStorage.getItem(key)||'{}');}catch{return {};}})()).current;
 const [mode,setMode]=useState<NormalizeSettings['mode']>(saved.mode||'longest'),[width,setWidth]=useState(saved.width||1024),[height,setHeight]=useState(saved.height||1024),[upscale,setUpscale]=useState(!!saved.upscale),[alignment,setAlignment]=useState(saved.alignment??8);
 const [useAI,setUseAI]=useState(!!saved.useAI),[upscaleModel,setUpscaleModel]=useState(saved.upscaleModel||''),[useCaption,setUseCaption]=useState(!!saved.useCaption),[tagModel,setTagModel]=useState(saved.tagModel||'');
 const [threshold,setThreshold]=useState(saved.threshold??.35),[character,setCharacter]=useState(saved.character??.85),[removeCharacters,setRemoveCharacters]=useState(saved.removeCharacters??true),[captionMode,setCaptionMode]=useState(saved.captionMode||'append');
 const [pending,setPending]=useState(false),[error,setError]=useState(''),[preview,setPreview]=useState<NormalizePreview|null>(null),[caps,setCaps]=useState<any>(null),[job,setJob]=useState<any>({status:'idle'}),[showResult,setShowResult]=useState(false),[stopping,setStopping]=useState(false);
 const config:NormalizeSettings={project_id:projectId,relatives,mode,width,height,allow_upscale:upscale,alignment};const signature=JSON.stringify(config),current=useRef(signature);current.current=signature;
 const running=['starting','running'].includes(job.status),locked=pending||running;
 useEffect(()=>{setPreview(null);setShowResult(false);},[signature]);
 useEffect(()=>{localStorage.setItem(key,JSON.stringify({mode,width,height,upscale,alignment,useAI,upscaleModel,useCaption,tagModel,threshold,character,removeCharacters,captionMode}));},[mode,width,height,upscale,alignment,useAI,upscaleModel,useCaption,tagModel,threshold,character,removeCharacters,captionMode]);
 useEffect(()=>{let live=true;void desktop()?.preprocessing?.('capabilities').then(c=>{if(!live)return;setCaps(c);setUpscaleModel((v:string)=>c.upscale_models.includes(v)?v:c.upscale_models.find((n:string)=>n.includes('x2'))||c.upscale_models[0]||'');setTagModel((v:string)=>c.tag_models.some((m:any)=>m.id===v)?v:c.tag_models.find((m:any)=>m.name==='wd-v1-4-vit-tagger-v2')?.id||c.tag_models[0]?.id||'');}).catch(e=>{if(live)setError(desktopError(e));});void desktop()?.preprocessing?.('status',{project_id:projectId}).then(s=>{if(live){setJob(s);setShowResult(!!s.after_preview);}}).catch(e=>{if(live)setError(desktopError(e));});return()=>{live=false;};},[projectId]);
 useEffect(()=>{if(!running)return;let live=true;let timer:ReturnType<typeof setTimeout>;async function poll(){try{const next=await desktop()!.preprocessing('status',{project_id:projectId});if(live){setJob(next);if(['starting','running'].includes(next.status))timer=setTimeout(poll,1000);else setShowResult(!!next.after_preview);}}catch(e){if(live){setError(desktopError(e));timer=setTimeout(poll,2500);}}}timer=setTimeout(poll,500);return()=>{live=false;clearTimeout(timer);};},[running,projectId]);
 const valid=relatives.length>0&&relatives.length<=200&&width>=64&&width<=4096&&height>=64&&height<=4096&&Number.isInteger(width)&&Number.isInteger(height);
 async function inspect(){const version=signature;setPending(true);setError('');setShowResult(false);try{const result=await desktop()!.previewNormalize(config);if(current.current===version)setPreview(result);}catch(e){setError(desktopError(e));}finally{setPending(false);}}
 async function apply(){if(!preview)return;setPending(true);setError('');setStopping(false);setShowResult(false);try{if(!desktop()?.preprocessing){const result=await desktop()!.applyNormalize({...config,expected:preview.items});onCreated(result.folder,result.relatives);onClose();return;}setJob(await desktop()!.preprocessing('start',{...config,expected:preview.items,use_ai:useAI,upscale_model:upscaleModel,use_caption:useCaption,tag_model:tagModel,tag_options:{threshold,character_threshold:character,remove_characters:removeCharacters,mode:captionMode}}));}catch(e){setError(desktopError(e));}finally{setPending(false);}}
 const rectangular=mode==='pad'||mode==='crop',sideLabel=rectangular?'横幅':mode==='shortest'?'短辺':'長辺';
 const before=showResult?job.before_preview:preview?.before,after=showResult?job.after_preview:preview?.after;
 return <Dialog.Root open onOpenChange={v=>{if(!v&&!pending)onClose();}}><Dialog.Content maxWidth="780px"><Dialog.Title>サイズ正規化・前処理</Dialog.Title><Dialog.Description size="2" mb="4">選択した{relatives.length}枚を別フォルダへ作成します。原本と元のTXTは保持します。1回200枚まで。</Dialog.Description><Flex direction="column" gap="3">
 <Select.Root value={mode} onValueChange={v=>setMode(v as NormalizeSettings['mode'])} disabled={locked}><Select.Trigger aria-label="サイズの揃え方"/><Select.Content><Select.Item value="longest">長辺を揃える・縦横比を維持</Select.Item><Select.Item value="shortest">短辺を揃える・縦横比を維持</Select.Item><Select.Item value="pad">縦横を揃える・余白で調整</Select.Item><Select.Item value="crop">中央を切り抜いて縦横を揃える</Select.Item></Select.Content></Select.Root>
 <Flex gap="3" wrap="wrap"><label><Text as="div" size="1">{sideLabel}（px）</Text><NumericInput aria-label={sideLabel+'px'} min={64} max={4096} value={width} disabled={locked} onValueChange={setWidth}/></label>{rectangular&&<label><Text as="div" size="1">高さ（px）</Text><NumericInput aria-label="高さpx" min={64} max={4096} value={height} disabled={locked} onValueChange={setHeight}/></label>}<Flex align="end" gap="1">{[512,640,768,1024].map(v=><Button size="1" variant="soft" key={v} disabled={locked} onClick={()=>{setWidth(v);setHeight(v);}}>{v}</Button>)}</Flex></Flex>
 <Flex gap="3" wrap="wrap"><Text as="label" size="2"><Flex gap="2" align="center"><Checkbox checked={upscale} disabled={locked} onCheckedChange={v=>{setUpscale(v===true);if(v!==true)setUseAI(false);}}/>小さい画像も拡大する</Flex></Text><Text as="label" size="2"><Flex gap="2" align="center"><Checkbox checked={alignment===8} disabled={locked} onCheckedChange={v=>setAlignment(v===true?8:1)}/>学習用に8px単位へ揃える</Flex></Text></Flex>
 <Text size="1" color={mode==='crop'?'amber':'gray'}>{mode==='crop'?'中央クロップは画像の端を切り取ります。プレビューで構図を確認してください。':'拡大を許可しない場合、小さい画像は元の大きさ以下になります。8px単位では端数を切り下げます。'}</Text>
 {desktop()?.preprocessing&&<details><summary>AI拡大・処理後の自動タグ</summary><Flex direction="column" gap="3" mt="3"><Text as="label" size="2"><Flex gap="2" align="center"><Checkbox checked={useAI} disabled={locked||!upscale||!caps?.upscale_models?.length} onCheckedChange={v=>setUseAI(v===true)}/>拡大が必要な画像にAI拡大を使う</Flex></Text>{useAI&&<Select.Root value={upscaleModel||undefined} onValueChange={setUpscaleModel} disabled={locked}><Select.Trigger aria-label="AI拡大モデル" placeholder="モデルを選択"/><Select.Content>{caps?.upscale_models.map((n:string)=><Select.Item value={n} key={n}>{n}</Select.Item>)}</Select.Content></Select.Root>}{!caps?<Text size="1" color="gray">既存モデルの対応状況を確認中…</Text>:caps.comfy_error&&<Text size="1" color="gray">AI拡大：{caps.comfy_error}</Text>}
 <Text as="label" size="2"><Flex gap="2" align="center"><Checkbox checked={useCaption} disabled={locked||!caps?.tag_models?.length} onCheckedChange={v=>setUseCaption(v===true)}/>処理後の画像からタグを生成してTXTへ保存</Flex></Text>{useCaption&&<><Select.Root value={tagModel||undefined} onValueChange={setTagModel} disabled={locked}><Select.Trigger aria-label="処理後タグモデル" placeholder="モデルを選択"/><Select.Content>{caps?.tag_models.map((m:any)=><Select.Item value={m.id} key={m.id}>{m.name}</Select.Item>)}</Select.Content></Select.Root><Select.Root value={captionMode} onValueChange={setCaptionMode} disabled={locked}><Select.Trigger aria-label="処理後の既存タグ"/><Select.Content><Select.Item value="append">既存タグを残して追加</Select.Item><Select.Item value="replace">コピー側のタグを置換</Select.Item></Select.Content></Select.Root><Flex gap="3"><label><Text as="div" size="1">一般タグしきい値</Text><NumericInput aria-label="処理後一般タグしきい値" value={threshold} min={.05} max={.95} step={.05} disabled={locked} onValueChange={setThreshold}/></label><label><Text as="div" size="1">キャラタグしきい値</Text><NumericInput aria-label="処理後キャラタグしきい値" value={character} min={.05} max={.99} step={.05} disabled={locked||removeCharacters} onValueChange={setCharacter}/></label></Flex><Text as="label" size="2"><Checkbox checked={removeCharacters} disabled={locked} onCheckedChange={v=>setRemoveCharacters(v===true)}/> 推定キャラクター名を除外</Text></>}
 <Text size="1" color="gray">寸法プレビューでは切り抜き・サイズを確認します。AI処理の実画像と生成タグは実行後の結果に表示します。</Text></Flex></details>}
 {error&&<Callout.Root color="red"><Callout.Text>{error}</Callout.Text></Callout.Root>}
 {before&&after&&<><Text size="2" weight="medium">{showResult?'保存済みの処理結果':'寸法のプレビュー'}（先頭画像）</Text><div className="normalize-comparison"><figure><img src={before} alt="処理前のプレビュー"/><figcaption>処理前</figcaption></figure><figure><img src={after} alt={showResult?'前処理の実結果':'サイズ調整後のプレビュー'}/><figcaption>{showResult?'実処理後':'寸法調整後'}</figcaption></figure></div></>}
 {preview&&!showResult&&<Text size="1" color="gray">{preview.count}枚、{new Set(preview.items.map(i=>i.source_size.join('x'))).size}種類のサイズ → {new Set(preview.items.map(i=>i.output_size.join('x'))).size}種類。{preview.items.filter(i=>i.scale>1).length}枚が拡大対象。</Text>}
 {job.status!=='idle'&&<><Text role="status" size="2">{job.message}</Text>{running&&<><Progress value={job.total?100*job.done/job.total:0}/><Text size="1" color="gray">停止は処理中の1枚が終了した時点で反映します。</Text></>}<Flex gap="2" wrap="wrap">{job.results?.slice(0,12).map((r:any)=><Badge key={r.relative} color="gray">{r.relative.split('/').pop()} · {r.output_size.join('×')} {r.caption_generated?'· タグ生成':''}</Badge>)}</Flex>{job.errors?.map((e:any)=><Text color="red" size="1" key={e.relative}>{e.relative}：{e.message}</Text>)}</>}
 {caps&&<details><summary>使えない処理（文字削除・マスク）について</summary><Text as="p" size="1" color="gray">{caps.text_removal_reason}。旧版の文字削除は説明と異なるQwen処理を呼んでいたため、同じ機能として有効化していません。</Text><Text as="p" size="1" color="gray">{caps.masking_reason}。</Text></details>}
 <Flex justify="end" gap="3" wrap="wrap" mt="2"><Button variant="soft" color="gray" disabled={pending} onClick={onClose}>{running?'閉じる（処理は継続）':'閉じる'}</Button>{running?<Button color="amber" variant="soft" disabled={stopping} onClick={()=>{setStopping(true);void desktop()!.preprocessing('cancel',{project_id:projectId}).catch(e=>{setStopping(false);setError(desktopError(e));});}}>{stopping?'停止待ち':'処理を停止'}</Button>:<><Button variant="soft" disabled={!valid||pending} title={!valid?'幅・高さは64〜4096pxの整数で指定してください':undefined} onClick={()=>void inspect()}>{pending?<Spinner/>:null}寸法をプレビュー</Button><Button disabled={!preview||pending||(useAI&&(!upscale||!upscaleModel))||(useCaption&&!tagModel)} title={pending?'処理中です':!preview?'先に「寸法をプレビュー」で結果を確認すると実行できます':(useAI&&!upscale)?'AI拡大を使うには「小さい画像も拡大する」をオンにしてください':(useAI&&!upscaleModel)?'AI拡大モデルを選んでください':(useCaption&&!tagModel)?'タグ生成モデルを選んでください':undefined} onClick={()=>void apply()}>前処理を実行</Button></>}{job.folder_committed&&job.results?.length>0&&!running&&<Button variant="soft" onClick={()=>{onCreated(job.folder,job.results.map((r:any)=>r.relative));onClose();}}>結果フォルダを開く</Button>}</Flex>
 </Flex></Dialog.Content></Dialog.Root>;
}
