import {useEffect,useState} from 'react';
import {Button,Dialog,Flex,Text,Select,Spinner,Callout} from '@radix-ui/themes';
import {apiGet,apiDelete} from '../../lib/api';
type Checkpoint={id:number;epoch:number;step:number|null;file_path:string;validation_status?:string};
type Cache={busy:boolean;training:{files:number;bytes:number};preview:{files:number;bytes:number}};
export default function RunActions({runId,active,onContinue,onChanged}:{runId:number;active:boolean;onContinue:(id:number)=>void;onChanged:()=>void}){
 const [checkpoints,setCheckpoints]=useState<Checkpoint[]>([]),[selected,setSelected]=useState(''),[cache,setCache]=useState<Cache|null>(null),[open,setOpen]=useState(false),[kind,setKind]=useState<'training'|'preview'|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let live=true;void apiGet<{checkpoints:Checkpoint[]}>(`/training/runs/${runId}/checkpoints`).then(r=>{if(live){const items=r.checkpoints.filter(c=>c.validation_status!=='deleted').sort((a,b)=>b.epoch-a.epoch);setCheckpoints(items);setSelected(items[0]?String(items[0].id):'');}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[runId,active]);
 async function inspect(){setOpen(true);setError('');setCache(null);try{setCache(await apiGet(`/training/runs/${runId}/cleanup`));}catch(e){setError(String(e));}}
 async function remove(){if(!kind)return;setBusy(true);setError('');try{await apiDelete(`/training/runs/${runId}/cleanup/${kind}`);setKind(null);setCache(await apiGet(`/training/runs/${runId}/cleanup`));onChanged();}catch(e){setError(String(e));}finally{setBusy(false);}}
 return <details className="wb-run-actions"><summary>保存済みLoRAから継続・キャッシュ管理</summary><Flex direction="column" gap="2" mt="2">
  {checkpoints.length>0&&<><Select.Root value={selected} onValueChange={setSelected} disabled={active}><Select.Trigger aria-label="継続元の学習LoRA"/><Select.Content>{checkpoints.map(c=><Select.Item key={c.id} value={String(c.id)}>Epoch {c.epoch} · Step {c.step??'—'}</Select.Item>)}</Select.Content></Select.Root><Button size="1" variant="soft" disabled={active||!selected} title={active?'学習・生成の実行中は使えません':!selected?'継続元のエポックを選んでください':undefined} onClick={()=>onContinue(Number(selected))}>このLoRAを次の学習の初期値にする</Button><Text size="1" color="gray">左の設定で追加学習します。重みだけを引き継ぎ、Optimizer状態・エポック番号は復元しません。元のRunは保持します。</Text></>}
  <Button size="1" color="gray" variant="soft" disabled={active} title={active?'学習・生成の実行中は使えません':'このRunだけのキャッシュ容量を確認して削除します（複数Runをまとめて整理するときは下の「過去Run・キャッシュを一括整理」）'} onClick={()=>void inspect()}>このRunのキャッシュを確認・削除</Button>
 </Flex><Dialog.Root open={open} onOpenChange={v=>{if(!busy){setOpen(v);setKind(null);}}}><Dialog.Content maxWidth="560px"><Dialog.Title>Run #{runId} のキャッシュ管理</Dialog.Title><Dialog.Description size="2">学習済みLoRA、学習ログ、元画像、タグは保持します。</Dialog.Description>{!cache&&!error&&<Spinner/>}{cache&&<Flex direction="column" gap="3" mt="3">{(['training','preview'] as const).map(k=><Flex key={k} align="center" justify="between" gap="3"><Text size="2">{k==='training'?'前処理キャッシュ':'保存済みプレビュー画像'} · {cache[k].files}ファイル · {(cache[k].bytes/1048576).toFixed(1)} MB</Text><Button color="red" variant="soft" size="1" disabled={busy||cache.busy||!cache[k].files} onClick={()=>setKind(k)}>削除…</Button></Flex>)}{cache.busy&&<Text size="1" color="amber">実行中または生成待ちのため削除できません。</Text>}</Flex>}{kind&&<Callout.Root mt="3" color="amber"><Callout.Text>{kind==='training'?'前処理キャッシュを削除します。次に必要になったとき再計算されます。':'このRunの保存済みプレビュー画像を削除します。画像の自動復元は行いません。'}</Callout.Text><Button color="red" disabled={busy} onClick={()=>void remove()}>{busy?<Spinner/>:'この対象を削除する'}</Button></Callout.Root>}{error&&<Text as="p" color="red" size="1">{error}</Text>}<Flex justify="end" mt="4"><Button color="gray" variant="soft" disabled={busy} onClick={()=>{setOpen(false);setKind(null);}}>閉じる</Button></Flex></Dialog.Content></Dialog.Root></details>;
}
