import {useEffect,useRef,useState} from 'react';
import {Text,Callout} from '@radix-ui/themes';
import uPlot from 'uplot';
import 'uplot/dist/uPlot.min.css';
import {apiGet} from '../../lib/api';
type Points=Array<[number,number]>;
type Metrics={advanced_parameters?:Record<string,unknown>;source:string;parameter_source:string;series:Record<string,Points>;parameters:Record<string,string|number|null>;total_steps:number;warnings:string[];fingerprint:string;speed_source:string;time_origin:string|null};
function Plot({title,series,xLabel='Step',percent=false,zero=false}:{title:string;series:{name:string;points:Points;color:string}[];xLabel?:string;percent?:boolean;zero?:boolean}){
 const host=useRef<HTMLDivElement>(null),chart=useRef<uPlot|null>(null);
 const spec=series.map(s=>s.name+s.color).join('|'),hasData=series.some(s=>s.points.length),signature=JSON.stringify(series.map(s=>s.points));
 useEffect(()=>{if(!host.current||!series.some(s=>s.points.length))return;const xs=[...new Set(series.flatMap(s=>s.points.map(p=>p[0])))].sort((a,b)=>a-b);const data:uPlot.AlignedData=[xs,...series.map(s=>{const values=new Map(s.points);return xs.map(x=>values.get(x)??null);})];const format=(v:number)=>Math.abs(v)>0&&Math.abs(v)<.001?Number(v.toPrecision(3)).toString():Number(v.toPrecision(4)).toString();const plot=new uPlot({width:Math.max(240,host.current.clientWidth),height:240,scales:{x:{time:false},y:percent?{range:()=>[0,100]}:zero?{range:(_u,min,max)=>[0,Math.max(max*1.15,1e-8)]}:{}},axes:[{stroke:'#a4a4b4',font:'12px sans-serif',grid:{show:false},label:xLabel,labelSize:18},{stroke:'#a4a4b4',font:'12px sans-serif',size:72,grid:{stroke:'rgba(160,160,180,.13)'},values:(_u,values)=>values.map(format)}],series:[{label:xLabel,value:(_u,v)=>v==null?'—':format(v)},...series.map(s=>({label:s.name,stroke:s.color,width:s.name==='平均Loss'?2.5:1.5,points:{show:false},value:(_u:uPlot,v:number|null)=>v==null?'—':format(v)}))],legend:{show:true,live:true},hooks:{ready:[u=>u.setLegend({idx:u.data[0].length-1},false)],setCursor:[u=>u.setLegend({idx:u.cursor.idx??u.data[0].length-1},false)]},cursor:{drag:{x:false,y:false}}},data,host.current);chart.current=plot;const observer=new ResizeObserver(entries=>{const width=Math.floor(entries[0]?.contentRect.width||0);if(width>=100)plot.setSize({width,height:240});});observer.observe(host.current);return()=>{observer.disconnect();plot.destroy();chart.current=null;};},[spec,hasData,title,xLabel,percent,zero]);
 useEffect(()=>{if(!chart.current)return;const xs=[...new Set(series.flatMap(s=>s.points.map(p=>p[0])))].sort((a,b)=>a-b);chart.current.setData([xs,...series.map(s=>{const m=new Map(s.points);return xs.map(x=>m.get(x)??null);})],true);chart.current.setLegend({idx:chart.current.cursor.idx??xs.length-1},false);},[signature]);
 const count=Math.max(0,...series.map(s=>s.points.length));return <div className="wb-chart"><Text as="div" size="1" weight="medium">{title}</Text>{count?<div ref={host} role="img" aria-label={`${title}：実ログ ${count}点`} data-point-count={count}/>:<Text as="p" size="1" color="gray">この指標の実測ログはありません。</Text>}</div>;
}
export default function TrainingCharts({runId,epochs,active}:{runId:number;progress:number;epochs:number;active:boolean}){
 const [data,setData]=useState<Metrics|null>(null),[error,setError]=useState('');
 useEffect(()=>{let live=true;let timer:ReturnType<typeof setTimeout>;setData(null);async function poll(){try{const next=await apiGet<Metrics>(`/training/runs/${runId}/metrics`);if(live){setData(old=>old?.fingerprint===next.fingerprint?old:next);setError('');}}catch(e){if(live)setError(e instanceof Error?e.message:String(e));}finally{if(live)timer=setTimeout(poll,5000);}}void poll();return()=>{live=false;clearTimeout(timer);};},[runId]);
 const values=data?.series||{},params=data?.parameters;
 const samples=(values['speed/seconds']||[]).slice(-20).map(p=>p[1]).filter(v=>Number.isFinite(v)&&v>0);
 const seconds=samples.length?samples.reduce((a,b)=>a+b,0)/samples.length:null;
 const epochSeconds=seconds&&data&&epochs>0?seconds*data.total_steps/epochs:null;
 const speedLabel=active?'現在の速度（直近20step）':'終了時の速度（最終20step）';
 return <div className="wb-training-charts"><div aria-label="学習速度" className="wb-run-metrics"><span>{speedLabel}<b>{seconds===null?'計測値なし':`${seconds.toFixed(2)} 秒/step · ${(1/seconds).toFixed(2)} step/秒`}</b></span><span>1エポックの換算時間<b>{epochSeconds===null?'計測値なし':`${Math.floor(epochSeconds/60)}分${Math.round(epochSeconds%60)}秒 · ${(60/epochSeconds).toFixed(2)} epoch/分`}</b></span></div><details className="wb-training-analysis"><summary>詳しいグラフ・実行設定</summary>{error&&<Callout.Root color="red" size="1"><Callout.Text>{error}</Callout.Text></Callout.Root>}{data&&<><Text size="1" color="gray">{data.source==='tensorboard'?'TensorBoard実測':data.source==='text_log'?'学習ログから取得':'まだ測定値がありません'} · 通常は最新値、カーソルを重ねるとその時点の値</Text><div className="wb-chart-grid"><details className="wb-secondary-charts wb-loss-details"><summary>Loss（損失）の推移を見る</summary><Plot title="Lossの推移" series={[{name:'各stepのLoss',points:values['loss/current']||[],color:'rgba(184,164,255,.55)'},{name:'平均Loss',points:values['loss/average']||[],color:'#6bdbce'}].filter(s=>s.points.length)}/></details><details className="wb-secondary-charts"><summary>学習率・進捗・速度を見る</summary><Plot title="学習率の推移" zero series={Object.entries(values).filter(([tag])=>tag.startsWith('lr/')).map(([tag,points],i)=>({name:tag,points,color:i?'#6bdbce':'#f5c36a'}))}/><Plot title="進捗率の推移" xLabel="経過秒" percent series={[{name:'進捗 %',points:values['progress/percent']||[],color:'#8dafff'}]}/><Plot title="1stepの記録間隔（秒）" zero series={[{name:'秒/step',points:values['speed/seconds']||[],color:'#e8a7cc'}]}/></details></div><Text as="p" size="1" color="gray">{data.time_origin||'進捗の時刻情報は記録されていません。'}。記録間隔には保存などの待ち時間も含みます。</Text>{data.warnings.map(w=><Text as="p" key={w} size="1" color="amber">{w}</Text>)}</>}{params&&<details className="wb-run-parameters"><summary>{data?.parameter_source==='trainer_config'?'このRunの実行設定':'このRunの要求設定'}</summary><dl>{Object.entries({モデル:params.base_checkpoint_path,系統:params.model_family,解像度:params.resolution,Rank:params.rank,Alpha:params.alpha,バッチ:params.train_batch_size,学習回数:params.epochs,繰り返し:params.repeats,本体の開始学習率:params.body_learning_rate,基本設定の学習率:params.requested_learning_rate,初回の実測学習率:params.observed_initial_learning_rate,最新の実測学習率:params.observed_latest_learning_rate,Optimizer:params.optimizer,Scheduler:params.scheduler}).map(([name,value])=><div key={name}><dt>{name}</dt><dd>{value??'記録なし'}</dd></div>)}</dl>{data?.advanced_parameters&&<dl>{Object.entries(data.advanced_parameters).map(([name,value])=><div key={name}><dt>{name}</dt><dd>{typeof value==='boolean'?(value?'有効':'無効'):Array.isArray(value)?value.join(', '):String(value)}</dd></div>)}</dl>}</details>}</details></div>;
}
