import {useEffect,useState} from 'react';
import {Button,Flex,Text,TextField,Spinner} from '@radix-ui/themes';
import {apiGet,apiPost} from '../../lib/api';
type Instance={id:number;name:string;trigger_token:string;matched:number};
type State={trigger_token:string;caption_count:number;matched:number;candidates:{token:string;count:number}[];instances:Instance[];instance_unassigned:number;instance_multiple:number};
// 古いサーバー応答（instances なし）でも画面全体が落ちないよう既定値を補う。
const normalize=(s:State):State=>({...s,instances:s.instances??[],instance_unassigned:s.instance_unassigned??0,instance_multiple:s.instance_multiple??0});
export default function TrainingTrigger({projectId,onSaved}:{projectId:number;onSaved:()=>void}){
 const [state,setState]=useState<State|null>(null),[value,setValue]=useState(''),[pending,setPending]=useState(false),[error,setError]=useState(''),[newName,setNewName]=useState(''),[newToken,setNewToken]=useState('');
 useEffect(()=>{let live=true;apiGet<State>(`/training/trigger/${projectId}`).then(raw=>{const s=normalize(raw);if(live){setState(s);setValue(s.trigger_token);}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[projectId]);
 async function save(){setPending(true);setError('');try{const s=normalize(await apiPost<State>(`/training/trigger/${projectId}`,{trigger_token:value},'PUT'));setState(s);setValue(s.trigger_token);onSaved();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setPending(false);}}
 async function run(task:()=>Promise<State>){setPending(true);setError('');try{setState(normalize(await task()));onSaved();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setPending(false);}}
 const addInstance=()=>run(async()=>{const s=await apiPost<State>(`/training/instances/${projectId}`,{name:newName.trim()||newToken.trim(),trigger_token:newToken},'POST');setNewName('');setNewToken('');return s;});
 const editInstance=(i:Instance,name:string,token:string)=>run(()=>apiPost<State>(`/training/instances/${projectId}/${i.id}`,{name,trigger_token:token},'PUT'));
 const removeInstance=(i:Instance)=>run(()=>apiPost<State>(`/training/instances/${projectId}/${i.id}`,{},'DELETE'));
 return <div className="wb-trigger"><Text as="label" size="1" htmlFor={`trigger-${projectId}`}>トリガーワード（呼び出しタグ）</Text><Flex gap="2" mt="1"><TextField.Root id={`trigger-${projectId}`} aria-label="トリガーワード" style={{flex:1}} placeholder="例：WASABI" value={value} disabled={!state||pending} onChange={e=>{setValue(e.target.value);setError('');}} onKeyDown={e=>{if(e.key==='Enter'&&!e.nativeEvent.isComposing&&value.trim())void save();}}/><Button variant="soft" disabled={!state||pending||!value.trim()||value.trim()===state.trigger_token} title={!state||pending?'読み込み中です':!value.trim()?'トリガーワードを入力すると登録できます':value.trim()===state.trigger_token?'登録済みの内容と同じです（変更すると登録できます）':'このトリガーワードを登録します'} onClick={()=>void save()}>{pending?<Spinner/>:null}登録</Button></Flex>{state&&<Text as="p" size="1" color={state.trigger_token&&state.matched===state.caption_count?'gray':'amber'}>{state.trigger_token?`登録済み：${state.trigger_token} · 学習対象のキャプション ${state.matched}/${state.caption_count}枚に含まれています`:'管理用の登録はまだありません。キャプション先頭の候補から選べます。'}</Text>}{state&&!state.trigger_token&&<Flex gap="2" wrap="wrap">{state.candidates.map(c=><Button key={c.token} size="1" variant="soft" color="gray" onClick={()=>setValue(c.token)}>{c.token}（{c.count}/{state.caption_count}枚）</Button>)}</Flex>}{state?.trigger_token&&state.matched<state.caption_count&&<Text as="p" size="1" color="amber">登録だけでは画像のタグは変わりません。必要な画像に同じタグを追加し、学習対象を更新してください。</Text>}{state&&<div className="wb-instances"><Text as="div" size="1" weight="bold" mt="3">インスタンス（衣装などを別トリガーで学習）</Text><Text as="p" size="1" color="gray">同じキャラクターでも、衣装ごとに別のトリガーを付けて学習できます。上の共通トリガーは全画像に、インスタンスは画像ごとに1つだけ付けます。画像への割り当ては、データセットで画像を選び「タグ編集 → 選択した画像のタグを編集 → インスタンス」で行います。</Text>{state.instances.map(i=><InstanceRow key={`${i.id}:${i.name}:${i.trigger_token}`} item={i} total={state.caption_count} disabled={pending} onSave={(n,t)=>void editInstance(i,n,t)} onRemove={()=>void removeInstance(i)}/>)}<Flex gap="2" mt="2"><TextField.Root aria-label="インスタンス名" style={{flex:1}} placeholder="名前（例：制服）" value={newName} disabled={pending} onChange={e=>setNewName(e.target.value)}/><TextField.Root aria-label="インスタンスのトリガーワード" style={{flex:1}} placeholder="トリガー（例：WASABI_uniform）" value={newToken} disabled={pending} onChange={e=>setNewToken(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.nativeEvent.isComposing&&newToken.trim())void addInstance();}}/><Button variant="soft" disabled={pending||!newToken.trim()} title={!newToken.trim()?'トリガーを入力すると追加できます':'インスタンスを追加します'} aria-label="インスタンスを追加" onClick={()=>void addInstance()}>追加</Button></Flex>{state.instances.length>0&&(state.instance_unassigned>0||state.instance_multiple>0)&&<Text as="p" size="1" color="amber">インスタンス未割当 {state.instance_unassigned}枚 / 複数割当 {state.instance_multiple}枚。画像ごとにどれか1つだけ付けてください。</Text>}</div>}{error&&<Text as="p" size="1" color="red">{error}</Text>}</div>;
}
function InstanceRow({item,total,disabled,onSave,onRemove}:{item:Instance;total:number;disabled:boolean;onSave:(name:string,token:string)=>void;onRemove:()=>void}){
 const [name,setName]=useState(item.name),[token,setToken]=useState(item.trigger_token);
 const dirty=name.trim()!==item.name||token.trim()!==item.trigger_token;
 return <Flex gap="2" mt="2" align="center"><TextField.Root aria-label={`${item.name}の名前`} style={{flex:1}} value={name} disabled={disabled} onChange={e=>setName(e.target.value)}/><TextField.Root aria-label={`${item.name}のトリガーワード`} style={{flex:1}} value={token} disabled={disabled} onChange={e=>setToken(e.target.value)}/><Text size="1" color="gray" style={{whiteSpace:'nowrap'}}>{item.matched}/{total}枚</Text>{dirty&&<Button variant="soft" disabled={disabled||!token.trim()} title={!token.trim()?'トリガーを入力してください':undefined} aria-label={`${item.name}の変更を保存`} onClick={()=>onSave(name,token)}>保存</Button>}<Button variant="ghost" color="red" disabled={disabled} aria-label={`${item.name}を削除`} onClick={onRemove}>削除</Button></Flex>;
}
