pretrained_model_name_or_path = "C:\\Users\\Keishi\\AI_tools\\ComfyUI-Portable\\ComfyUI_windows_portable\\ComfyUI\\models\\diffusion_models\\anima-base-v1.0.safetensors"
qwen3 = "C:\\Users\\Keishi\\AI_tools\\ComfyUI-Portable\\ComfyUI_windows_portable\\ComfyUI\\models\\text_encoders\\qwen_3_06b_base.safetensors"
vae = "C:\\Users\\Keishi\\AI_tools\\ComfyUI-Portable\\ComfyUI_windows_portable\\ComfyUI\\models\\vae\\qwen_image_vae.safetensors"
train_data_dir = "C:\\Users\\Keishi\\Portfolio\\Generation\\Training\\LoRA-Studio-Next\\projects\\Keytar Fox Character\\dataset"
output_dir = "C:\\Users\\Keishi\\Portfolio\\Generation\\Training\\LoRA-Studio-Next\\projects\\Keytar Fox Character\\outputs"
output_name = "anima_lora"
save_model_as = "safetensors"
resolution = "1024,1024"
network_module = "networks.lora_anima"
network_dim = 16
network_alpha = 16.0
max_train_epochs = 6
save_every_n_epochs = 1
train_batch_size = 1
caption_extension = ".txt"
optimizer_type = "AdamW8bit"
lr_scheduler = "constant"
learning_rate = 0.0001
timestep_sampling = "sigmoid"
discrete_flow_shift = 1.0
mixed_precision = "bf16"
save_precision = "bf16"
gradient_checkpointing = true
cache_latents = true
network_train_unet_only = true
cache_text_encoder_outputs = true
cache_text_encoder_outputs_to_disk = true
vae_disable_cache = true
qwen_image_vae_2d = true
persistent_data_loader_workers = true
max_data_loader_n_workers = 4
enable_bucket = true
min_bucket_reso = 256
max_bucket_reso = 2048
bucket_reso_steps = 64
logging_dir = "C:\\Users\\Keishi\\Portfolio\\Generation\\Training\\LoRA-Studio-Next\\docs\\shared-models-20260920\\logs"
