import NumericInput from './NumericInput';
import {useEffect,useState,useRef} from 'react';
import {Button,Dialog,Flex,Text,TextField,TextArea,Select,Callout,Spinner,Badge} from '@radix-ui/themes';
import {desktop,desktopError} from './desktopBridge';
import ModelPicker from './ModelPicker';
type Model={id:string;name:string;category:string;path:string|null};
type Catalog={root:string;url:string;models:Model[];loras:string[];workflows:{name:string;path:string}[];devices:{name:string}[]};
type Props={projectId:number;basePath:string;family:string;onClose:()=>void;onBind:()=>void};
export default function ComfyPreviewDialog({projectId,basePath,family:initialFamily,onClose,onBind}:Props){
 const [family,setFamily]=useState(initialFamily);
 const [initializing,setInitializing]=useState(true);
 const [root,setRoot]=useState(''),[url,setUrl]=useState(''),[instances,setInstances]=useState<{url:string;root:string;device:string}[]>([]),[catalog,setCatalog]=useState<Catalog|null>(null);
 const [error,setError]=useState(''),[pending,setPending]=useState(false),[model,setModel]=useState(''),[lora,setLora]=useState('none'),[learned,setLearned]=useState<{id:number;file_path:string;epoch:number}[]>([]);
 const [positive,setPositive]=useState('1girl, animal ears, jacket, standing, full body, simple background'),[negative,setNegative]=useState('low quality, blurry'),[width,setWidth]=useState(512),[height,setHeight]=useState(512),[steps,setSteps]=useState(20),[cfg,setCfg]=useState(5),[seed,setSeed]=useState(42);
 const [workflow,setWorkflow]=useState('auto'),[graph,setGraph]=useState<Record<string,unknown>|null>(null),[job,setJob]=useState<any>({status:'idle'});
 const workflowInput=useRef<HTMLInputElement>(null);
 const draftKey=`studio:preview-draft:${projectId}`;
 const running=['starting','queued','running'].includes(job.status);
 const matchesFamily=(m:Model,f=family)=>f==='anima'?/anima(?!gine)/i.test(m.name):f==='sdxl'?m.category==='checkpoints'&&/illustrious|sdxl|animagine/i.test(m.name):/krea|redmix/i.test(m.name);
 useEffect(()=>{let live=true;Promise.all([desktop()!.comfy('discover'),desktop()!.comfy('checkpoints',{project_id:projectId}),desktop()!.comfy('preview-status',{project_id:projectId})]).then(async([found,outputs,state])=>{if(!live)return;setRoot(found.root);setUrl(found.url);setInstances(found.instances);setLearned(outputs.checkpoints);setJob(state);let stored:any=null;try{stored=JSON.parse(localStorage.getItem(draftKey)||'null');}catch{}const previous=stored?.version===1?stored:state.settings?.family===family?state.settings:null;if(previous){if(previous.family)setFamily(previous.family);setPositive(previous.positive||"");setNegative(previous.negative||"");setWidth(previous.width??512);setHeight(previous.height??512);setSteps(previous.steps??20);setCfg(previous.cfg??5);setSeed(previous.seed??42);setWorkflow(previous.workflow_name||"auto");setGraph(previous.graph||null);setLora(previous.checkpoint_id?"learned:"+previous.checkpoint_id:previous.lora?"comfy:"+previous.lora:"none");}try{const c=await desktop()!.comfy('inspect');if(live){setCatalog(c);if(previous&&c.models.some((m:Model)=>m.id===previous.model))setModel(previous.model);else chooseModel(c,previous?.family||family);}}catch(e){if(live)setError(desktopError(e));} }).catch(e=>{if(live)setError(desktopError(e));}).finally(()=>{if(live)setInitializing(false);});return()=>{live=false;};},[projectId]);
 function chooseModel(c:Catalog,f=family){const choices=c.models.filter(m=>matchesFamily(m,f));const clean=(p:string)=>p.replace(/\\/g,'/').toLowerCase();const same=choices.find(m=>m.path&&clean(m.path)===clean(basePath));const basename=basePath.split(/[\\/]/).pop();const candidates=choices.filter(m=>m.name.split(/[\\/]/).pop()===basename);setModel(same?.id||(candidates.length===1?candidates[0].id:'')||choices.find(m=>f==='anima'?m.name==='anima-base-v1.0.safetensors':f==='sdxl'?/illustrious/i.test(m.name):/redmix/i.test(m.name))?.id||'');}
 useEffect(()=>{if(!running)return;let live=true;let timer:ReturnType<typeof setTimeout>;async function poll(){try{const next=await desktop()!.comfy('preview-status',{project_id:projectId});if(live){setJob(next);if(['starting','queued','running'].includes(next.status))timer=setTimeout(poll,1000);}}catch(e){if(live){setError(desktopError(e));timer=setTimeout(poll,3000);}}}timer=setTimeout(poll,500);return()=>{live=false;clearTimeout(timer);};},[running,projectId]);
 async function bind(){setPending(true);setError('');try{const c=await desktop()!.comfy('bind',{root,url});setCatalog(c);chooseModel(c);setWorkflow('auto');setGraph(null);onBind();}catch(e){setError(desktopError(e));}finally{setPending(false);}}
 async function chooseWorkflow(value:string){if(value==='auto'){setWorkflow(value);setGraph(null);return;}setPending(true);setError('');try{const result=await desktop()!.loadComfyWorkflow(value);setGraph(result.graph);setWorkflow(value);}catch(e){setError(desktopError(e));}finally{setPending(false);}}
 async function importWorkflow(file:File){setPending(true);setError('');try{if(file.size>10*1024*1024)throw Error('ワークフローは10MB以下にしてください');const result=await desktop()!.compileComfyWorkflow({data:JSON.parse(await file.text()),name:file.name});setGraph(result.graph);setWorkflow('file:'+file.name);}catch(e){setError(desktopError(e));}finally{setPending(false);if(workflowInput.current)workflowInput.current.value='';}}
 async function generate(){setPending(true);setError('');try{setJob(await desktop()!.comfy('preview-start',{project_id:projectId,model,family,lora:lora.startsWith('comfy:')?lora.slice(6):'',checkpoint_id:lora.startsWith('learned:')?Number(lora.slice(8)):null,positive,negative,width,height,steps,cfg,seed,graph:graph||undefined,workflow_name:workflow}));}catch(e){setError(desktopError(e));}finally{setPending(false);}}
 useEffect(()=>{if(initializing)return;try{localStorage.setItem(draftKey,JSON.stringify({version:1,family,model,positive,negative,width,height,steps,cfg,seed,workflow_name:workflow,graph,lora:lora.startsWith('comfy:')?lora.slice(6):'',checkpoint_id:lora.startsWith('learned:')?Number(lora.slice(8)):null}));}catch{setError('入力したプレビュー設定を保存できませんでした。');}},[initializing,draftKey,family,model,positive,negative,width,height,steps,cfg,seed,workflow,graph,lora]);
 const relevant=catalog?.models.filter(m=>matchesFamily(m))||[];
 return <Dialog.Root open onOpenChange={v=>{if(!v&&!pending)onClose();}}><Dialog.Content maxWidth="820px"><Dialog.Title>ComfyUI接続・手動テスト生成</Dialog.Title><Dialog.Description size="2" mb="4">ここではボタンを押した時点で画像を生成します。学習中の自動プレビューの設定は、学習画面の「プレビュー設定」で行います。</Dialog.Description><Flex direction="column" gap="3">
 {initializing&&<Flex gap="2" align="center"><Spinner/><Text size="2" role="status">接続先とモデル一覧を読み込み中…</Text></Flex>}<details open={!catalog&&!initializing}><summary>{catalog?`接続済み · ${catalog.models.length}モデル · ${catalog.url}`:'ComfyUIへ接続'}</summary><Flex direction="column" gap="3" mt="3">{!!instances.length&&<Flex gap="2" wrap="wrap">{instances.map(i=><Button key={i.url} variant="soft" size="1" disabled={pending||running} onClick={()=>{setRoot(i.root);setUrl(i.url);setCatalog(null);}}>起動中 {i.url}</Button>)}</Flex>}<label><Text as="div" size="1">ComfyUI本体フォルダ</Text><Flex gap="2"><TextField.Root style={{flex:1}} aria-label="ComfyUI本体フォルダ" value={root} disabled={pending||running} onChange={e=>{setRoot(e.target.value);setCatalog(null);}}/><Button variant="soft" disabled={pending||running} onClick={()=>{void desktop()!.chooseComfyRoot().then(path=>{if(path){setRoot(path);setCatalog(null);}}).catch(e=>setError(desktopError(e)));}}>選択</Button></Flex></label><label><Text as="div" size="1">接続先URL</Text><TextField.Root aria-label="ComfyUI接続先URL" value={url} disabled={pending||running} onChange={e=>{setUrl(e.target.value);setCatalog(null);}}/></label><Button disabled={pending||running||!root||!url} onClick={()=>void bind()}>{pending?<Spinner/>:null}接続してモデル一覧を読み込む</Button></Flex></details>
 {catalog&&<><Flex gap="2" wrap="wrap"><Badge color="green">接続済み</Badge>{catalog.devices.map((d,i)=><Text key={i} size="1" color="gray">{d.name}</Text>)}</Flex><Text size="1" color="gray">ベースモデルのコピーは作りません。テキストエンコーダー・VAEは対応する組合せを接続先から取得します。</Text>
 <label><Text as="div" size="1">プレビューのモデル系統（学習設定は変更しません）</Text><Select.Root value={family} disabled={pending||running} onValueChange={v=>{setFamily(v);setModel('');setLora('none');setWorkflow('auto');setGraph(null);}}><Select.Trigger aria-label="プレビューのモデル系統"/><Select.Content><Select.Item value="anima">Anima</Select.Item><Select.Item value="sdxl">Illustrious / SDXL</Select.Item><Select.Item value="krea2">KREA2 RedMix</Select.Item></Select.Content></Select.Root></label>
 <Text size="1" color="gray">生成用ワークフロー：Anima・SDXLは自動構成で使えます。JSONはComfyUIの画像生成手順です。学習設定やモデル一覧の読込ではありません。</Text>
 <Flex gap="2" wrap="wrap"><Select.Root value={workflow} onValueChange={v=>void chooseWorkflow(v)} disabled={pending||running}><Select.Trigger aria-label="プレビューワークフロー"/><Select.Content><Select.Item value="auto" disabled={!['anima','sdxl'].includes(family)}>{family==='anima'?'Anima · 自動構成':family==='sdxl'?'Illustrious / SDXL · 自動構成':'ワークフローを選択'}</Select.Item>{workflow.startsWith('file:')&&<Select.Item value={workflow}>{workflow.slice(5)}</Select.Item>}{catalog.workflows.map(w=><Select.Item key={w.path} value={w.path}>{w.name}</Select.Item>)}</Select.Content></Select.Root><Button variant="soft" color="gray" disabled={pending||running} onClick={()=>workflowInput.current?.click()}>生成ワークフローJSONを読み込む</Button><input type="file" ref={workflowInput} accept=".json,application/json" aria-label="ワークフローJSONを読み込む" hidden onChange={e=>{if(e.target.files?.[0])void importWorkflow(e.target.files[0]);}}/></Flex>
 {graph?<Callout.Root><Callout.Text>選択したワークフロー内のモデル・プロンプト・サイズをそのまま使用します。出力画像はLoRA Studioへ保存します。{Object.keys(graph).length}ノード</Callout.Text></Callout.Root>:<>
 <ModelPicker value={catalog.models.find(m=>m.id===model)?.path||model} choices={relevant.map(m=>({path:m.path||m.id,name:m.name,source:m.category}))} onChange={value=>setModel(relevant.find(m=>(m.path||m.id)===value)?.id||'')} onRefresh={async()=>{const c=await desktop()!.comfy('inspect');setCatalog(c);}}/>
 <label><Text as="div" size="1">今回の手動生成で使うLoRA（1つ）</Text><Select.Root value={lora} onValueChange={setLora} disabled={pending||running}><Select.Trigger style={{width:'100%'}} aria-label="プレビューLoRA"/><Select.Content><Select.Item value="none">LoRAなし（ベースモデルだけで生成）</Select.Item>{learned.map(item=><Select.Item key={item.id} value={'learned:'+item.id}>学習出力 · Epoch {item.epoch} · {item.file_path.split(/[\\/]/).pop()}</Select.Item>)}{catalog.loras.filter(name=>family==='anima'?/anima/i.test(name):family==='sdxl'?!/anima|krea/i.test(name):/krea/i.test(name)).map(name=><Select.Item key={name} value={'comfy:'+name}>{name}</Select.Item>)}</Select.Content></Select.Root></label>
 <Text size="1" color="gray">学習中のLoRAは自動追加されません。学習結果を試す場合は「学習出力 · Epoch…」を選択してください。追加LoRAを重ねる欄ではありません。</Text>
 {lora.startsWith('learned:')&&<Text size="1" color="gray">学習LoRAは共有リンクで参照します。モデルの実体は複製しません。</Text>}
 <label><Text as="div" size="1">プロンプト</Text><TextArea aria-label="プレビュープロンプト" value={positive} disabled={pending||running} onChange={e=>setPositive(e.target.value)}/></label><label><Text as="div" size="1">ネガティブ</Text><TextArea aria-label="プレビューネガティブ" value={negative} disabled={pending||running} onChange={e=>setNegative(e.target.value)}/></label>
 <Flex gap="2" wrap="wrap">{[['幅',width,setWidth],['高さ',height,setHeight],['Steps',steps,setSteps],['CFG',cfg,setCfg],['Seed',seed,setSeed]].map(([label,value,fn])=><label key={String(label)} style={{width:100}}><Text as="div" size="1">{String(label)}</Text><NumericInput aria-label={'プレビュー'+label} value={Number(value)} disabled={pending||running} onValueChange={fn as (v:number)=>void}/></label>)}</Flex></>}
 <Button disabled={pending||running||(!graph&&(!model||!['anima','sdxl'].includes(family)))} onClick={()=>void generate()}>{pending||running?<Spinner/>:null}{running?'接続先で生成中':'今すぐ手動で画像を生成'}</Button></>}
 {error&&<Callout.Root color="red"><Callout.Text>{error}</Callout.Text></Callout.Root>}
 {job.status!=='idle'&&<Text size="2" role="status" color={job.status==='failed'?'red':undefined}>{job.message}{job.prompt_id?` · ${job.prompt_id.slice(0,8)}`:''}</Text>}
 {job.image&&<><Text size="1" color="gray">保存済みの生成結果：{job.settings?.workflow_name==='auto'?`${job.settings?.family} 自動構成`:String(job.settings?.workflow_name||'').split(/[\\/]/).pop()} · {job.prompt_id?.slice(0,8)}</Text><img src={job.image} alt="ComfyUIが生成したプレビュー" style={{display:'block',maxWidth:'100%',maxHeight:480,objectFit:'contain',borderRadius:8}}/><Text size="1" color="gray" style={{overflowWrap:'anywhere'}}>{job.image_path}</Text><Button variant="soft" color="gray" onClick={()=>{void desktop()!.comfy('reveal',{project_id:projectId}).catch(e=>setError(desktopError(e)));}}>プレビューの保存場所を開く</Button></>}
 <Flex justify="end"><Button variant="soft" color="gray" disabled={pending} onClick={onClose}>{running?'閉じる（生成は継続）':'閉じる'}</Button></Flex>
 </Flex></Dialog.Content></Dialog.Root>;
}
